// <auto-generated />
using System;
using ActividadApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActividadApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220152304_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ActividadApp.Models.Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int>("OrigenId")
                        .HasColumnType("int");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<int>("SistemaGestionId")
                        .HasColumnType("int");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAccionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntidadId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("Id");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("ProcesoId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("SistemaGestionId");

                    b.HasIndex("SitioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("ActividadApp.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Fecha")
                        .HasColumnType("int");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<int>("SolucionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("SolucionId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("ActividadApp.Models.ConfirmacionPlanAccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccionId")
                        .HasColumnType("int");

                    b.Property<bool>("CumplioPlan")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DetallesCumplimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionId")
                        .IsUnique();

                    b.HasIndex("ResponsableId");

                    b.ToTable("ConfirmacionesPlanAccion");
                });

            modelBuilder.Entity("ActividadApp.Models.Eficacia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccionId")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Eficaz")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionId")
                        .IsUnique();

                    b.ToTable("Eficacias");
                });

            modelBuilder.Entity("ActividadApp.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("ActividadApp.Models.Maestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("ActividadApp.Models.Proceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Procesos");
                });

            modelBuilder.Entity("ActividadApp.Models.ResponsableProceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ResponsablesProceso");
                });

            modelBuilder.Entity("ActividadApp.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ActividadApp.Models.Solucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccionId")
                        .HasColumnType("int");

                    b.Property<string>("AnalisisCausa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CorreccionPropuesta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCompromiso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInvestigacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioCoordinaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioInvestigaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionId")
                        .IsUnique();

                    b.HasIndex("UsuarioCoordinaId");

                    b.HasIndex("UsuarioInvestigaId");

                    b.ToTable("Soluciones");
                });

            modelBuilder.Entity("ActividadApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("RolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ActividadApp.Models.Accion", b =>
                {
                    b.HasOne("ActividadApp.Models.Maestro", null)
                        .WithMany()
                        .HasForeignKey("EntidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Maestro", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Maestro", null)
                        .WithMany()
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Maestro", null)
                        .WithMany()
                        .HasForeignKey("SistemaGestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Maestro", null)
                        .WithMany()
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Usuario", "Usuario")
                        .WithMany("Acciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Proceso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ActividadApp.Models.Actividad", b =>
                {
                    b.HasOne("ActividadApp.Models.Usuario", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Solucion", null)
                        .WithMany("Actividades")
                        .HasForeignKey("SolucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("ActividadApp.Models.ConfirmacionPlanAccion", b =>
                {
                    b.HasOne("ActividadApp.Models.Accion", null)
                        .WithOne("ConfirmacionPlanAccion")
                        .HasForeignKey("ActividadApp.Models.ConfirmacionPlanAccion", "AccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Usuario", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("ActividadApp.Models.Eficacia", b =>
                {
                    b.HasOne("ActividadApp.Models.Accion", null)
                        .WithOne("Eficacia")
                        .HasForeignKey("ActividadApp.Models.Eficacia", "AccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActividadApp.Models.Proceso", b =>
                {
                    b.HasOne("ActividadApp.Models.ResponsableProceso", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("ActividadApp.Models.Solucion", b =>
                {
                    b.HasOne("ActividadApp.Models.Accion", null)
                        .WithOne("Solucion")
                        .HasForeignKey("ActividadApp.Models.Solucion", "AccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Usuario", "UsuarioCoordina")
                        .WithMany()
                        .HasForeignKey("UsuarioCoordinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Usuario", "UsuarioInvestiga")
                        .WithMany()
                        .HasForeignKey("UsuarioInvestigaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCoordina");

                    b.Navigation("UsuarioInvestiga");
                });

            modelBuilder.Entity("ActividadApp.Models.Usuario", b =>
                {
                    b.HasOne("ActividadApp.Models.Maestro", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Maestro", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Maestro", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActividadApp.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Cargo");

                    b.Navigation("Organizacion");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ActividadApp.Models.Accion", b =>
                {
                    b.Navigation("ConfirmacionPlanAccion")
                        .IsRequired();

                    b.Navigation("Eficacia")
                        .IsRequired();

                    b.Navigation("Solucion")
                        .IsRequired();
                });

            modelBuilder.Entity("ActividadApp.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ActividadApp.Models.Solucion", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("ActividadApp.Models.Usuario", b =>
                {
                    b.Navigation("Acciones");
                });
#pragma warning restore 612, 618
        }
    }
}
